---
- name: Multi-Subnet IPAM + GCP Provisioning (Production Ready)
  hosts: 192.168.116.129
  gather_facts: no
  connection: ssh

  vars_files:
    - vars/common.yml
    - vars/paths.yml
    - vars/email.yml

  vars:
    region_map:
      AO: asia-south1
      EU: europe-west1
      AS: asia-east1
      NA: us-central1

  tasks:
    # ----------------------------------------------------------
    # VALIDATION
    # ----------------------------------------------------------
    - name: Validate subnets input exists
      fail:
        msg: "'subnets' variable missing"
      when: subnets is not defined

    - name: Validate subnets is list
      fail:
        msg: "'subnets' should be a list"
      when: subnets is not iterable

    - name: Validate max subnets per execution
      fail:
        msg: "Max 50 subnets per execution"
      when: subnets | length > 50


    # ----------------------------------------------------------
    # INITIALIZE REPORT LIST
    # ----------------------------------------------------------
    - name: Init subnet_report
      set_fact:
        subnet_report: []


    # ----------------------------------------------------------
    # READ CSV FILES (ON TARGET HOST, NOT LOCALHOST)
    # ----------------------------------------------------------
    - name: Read Env.csv from target host
      community.general.read_csv:
        path: "{{ env_csv }}"
      run_once: true
      register: env_raw

    - name: Set env_data fact
      set_fact:
        env_data: "{{ env_raw.list }}"
      run_once: true

    - name: Read Subnet.csv from target host
      community.general.read_csv:
        path: "{{ subnet_csv }}"
      run_once: true
      register: subnet_raw

    - name: Set subnet_data fact
      set_fact:
        subnet_data: "{{ subnet_raw.list }}"
      run_once: true


    # ----------------------------------------------------------
    # PROCESS EACH SUBNET
    # ----------------------------------------------------------
    - name: Process each subnet request
      include_role:
        name: gcp_subnet_multi
      loop: "{{ subnets }}"
      loop_control:
        loop_var: req
        index_var: batch_index


    # ----------------------------------------------------------
    # GENERATE HTML REPORT (RUN ON CONTROLLER)
    # ----------------------------------------------------------
    - name: Render HTML report locally
      template:
        src: "templates/subnet_report.html.j2"
        dest: "/tmp/subnet_report.html"
      delegate_to: localhost
      run_once: true


    # ----------------------------------------------------------
    # SEND EMAIL (RUN ON CONTROLLER)
    # ----------------------------------------------------------
    - name: Send HTML email
      mail:
        host: "{{ email_smtp.host }}"
        port: "{{ email_smtp.port }}"
        username: "{{ email_user }}"
        password: "{{ email_password }}"
        to: "{{ email_to }}"
        subject: "GCP Multi-Subnet Creation Report"
        subtype: html
        body: "{{ lookup('file', '/tmp/subnet_report.html') }}"
      delegate_to: localhost
      run_once: true
